name: Build and push to ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_ecr:
    runs-on: prd-devops-gha-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 058264138725.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker Image
        run: |
          docker build -t prd-barkuni-repo:latest 058264138725.dkr.ecr.us-east-1.amazonaws.com/prd-barkuni-repo:prd-flask-app-1 .

      - name: Push to ECR
        run: |
          docker push 058264138725.dkr.ecr.us-east-1.amazonaws.com/prd-barkuni-repo:prd-flask-app-1
